baseurl: https://fadhilyori.my.id
theme: PaperMod
paginate: 5
title: Fadhil Yori

# GA Tracking ID
googleAnalytics: G-VE4FZCJFS6

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: en

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: Fadhil Yori
    description: "Fadhil Yori Personal Site"
    keywords: [Blog, Portofolio]
    author: Fadhil Yori
    # DateFormat: "2 January 2006"

    defaultTheme: auto
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true
    UseHugoToc: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    assets:
        favicon: favicon2.ico
        disableHLJS: true

    label:
        text: "Fadhil Yori"
        icon: favicon2.ico

        # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Fadhil Yori
        subtitle: "Passionate about technology and constantly learning in the ever-evolving world of tech. I'm the Technology Infrastructure Lead at [Trustmedis](https://trustmedis.com), where I thrive in managing and optimizing infrastructure to support innovative solutions. Excited about collaborating on open-source projects and exploring new possibilities in the tech realm. I also manage [Buaya's repository server](https://buaya.klas.or.id) and [KLAS's](https://klas.or.id) services."
        imageUrl: "/img/avatar2.jpg"
        imageWidth: 240
        imageHeight: 240
        imageTitle: Fadhil Yori
        buttons:
            - name: Posts
              url: posts
            - name: Projects
              url: projects
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B, I'm Fadhil Yori"
        Content: Passionate about technology and constantly learning in the ever-evolving world of tech. I'm the Technology Infrastructure Lead at [Trustmedis](https://trustmedis.com), where I thrive in managing and optimizing infrastructure to support innovative solutions. Excited about collaborating on open-source projects and exploring new possibilities in the tech realm. I also manage [Buaya's repository server](https://buaya.klas.or.id) and [KLAS's](https://klas.or.id) services.

    socialIcons:
        - name: github
          url: "https://github.com/fadhilyori"
        - name: twitter
          url: "https://twitter.com/fadhilyori"
        - name: instagram
          url: "https://instagram.com/fadhilyori"
        - name: linkedin
          url: "https://www.linkedin.com/in/fadhil-yori-hibatullah"
        - name: email
          url: "mailto:me@fadhilyori.my.id"
        - name: leetcode
          url: "https://leetcode.com/fadhilyori/"

    cover:
        linkFullImages: false
        hidden: false
        hiddenInList: false
        hiddenInSingle: false

    editPost:
        URL: "https://github.com/fadhilyori/fadhilyori.github.io/issues"
        Text: "Suggest Changes"
        appendFilePath: false

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 10
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 20
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 30
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 40
        - identifier: search
          name: Search
          url: /search/
          weight: 50

pygmentsUseClasses: true
markup:
    highlight:
        noClasses: false
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai
